films/urls.py
from django.urls import path, re_path
from . import views


app_name = "films"

urlpatterns = [
    # /films/
    # re_path(r'^register/$', views.UserFormView.as_view(), name='register'),
    # /films/film/<id>/
    re_path(r'^film/(?P<pk>[0-9]+)/$', views.Detail_view.as_view(), name='detail'),
    # /films/film/<id>/rated/
    path('submit_review/<int:film_id>', views.rated, name='rated'),
    # /films/page=<page>/
    re_path(r'^allfilms/\w{0,100}$', views.pages, name='pages'),
    re_path(r'^hangman/$', views.minigame, name='minigame'),
    re_path(r'^search/$', views.search_bar, name='search'),
    # /films/top_100/
    re_path(r'^top100/$', views.Top100View.as_view(), name='top_100'),
    # /films/<genre>/
    # re_path(r'^(?P<genre>)/&', views.genre, name='genre'),
    re_path(r'^(?P<genre>[\w\-]+)/\w{0,100}$', views.GenreListView.as_view(), name='genre'),
    re_path(r'^$', views.IndexView.as_view(), name='index'),

]

filmweb/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('films.urls')),
]

films/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User


class Film(models.Model):
    title = models.CharField(_("title"), max_length=150, default=None)
    release_date = models.IntegerField(_("year"), default=None)
    genre = models.CharField(_("genre"), max_length=250, default=None)  # musi byc oddzielne przegladnie po rodzajach
    duration = models.IntegerField(_("duration"), default=None)
    country = models.CharField(_("country"), max_length=250, default=None)
    director = models.CharField(_("director"), max_length=70, default=None)  # oceny dla rezyserów??
    actors = models.CharField(_("actors"), max_length=1000, default=None)
    score = models.DecimalField(_("avg_vote"), decimal_places=3, max_digits=5, default=None)
    votes = models.IntegerField(_("votes"), default=None)
    poster = models.URLField(_("poster"), max_length=2000, default=None)
    # rated = models.IntegerField(default=None)

    def __str__(self):
        return f'{self.title} ({self.release_date})'


class Comment(models.Model):
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    comment = models.TextField(max_length=500, blank=True)
    rating = models.IntegerField()
    add_t = models.DateTimeField(auto_now_add=True)
    edit_t = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

films/forms.py
from .models import Comment
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rating']

films/views.py
from django.views.generic import ListView, DetailView, View
from .models import Film, Comment
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from .forms import UserForm
import random
from django.db.models import Q
from .forms import ReviewForm
from django.contrib import messages


class IndexView(ListView):
    model = Film
    context_object_name = 'films_db'
    # print(Film.objects.all().order_by('-release_date')[:9])

    def get_queryset(self):
        return Film.objects.all().order_by('-release_date')[:9]

    template_name = 'films/index.html'


class Detail_view(DetailView):
    model = Film
    context_object_name = 'film'
    template_name = 'films/detail.html'

    def get_context_data(self, **kwargs):
        context = super(Detail_view, self).get_context_data(**kwargs)
        hours = int(self.object.duration) // 60
        minutes = (int(self.object.duration) - hours * 60) % 60
        context['comments'] = context['film'].comment_set.all()
        context['actors_list'] = self.object.actors.split(", ")
        context['genre_list'] = self.object.genre.split(", ")
        context['duration'] = f'{hours} {"hours" if hours != 1 else "hour"} {minutes} {"minutes" if minutes != 1 else "minute"}'
        return context


class GenreListView(ListView):
    model = Film
    context_object_name = 'films_db'
    template_name = 'films/genres.html'

    def get_queryset(self):
        print(self.kwargs['genre'])
        return Film.objects.filter(genre__contains=self.kwargs['genre'].capitalize())

    def get_context_data(self, **kwargs):
        context = super(GenreListView, self).get_context_data(**kwargs)
        order_by = self.request.GET.get('order_by')
        page = self.request.GET.get('page')
        direction = self.request.GET.get('direction')
        ordering = order_by
        if direction == 'desc':
            ordering = '-{}'.format(ordering)
        films = Film.objects.filter(genre__contains=self.kwargs['genre'].capitalize()).order_by(ordering)

        paginator = Paginator(films, 60)
        try:
            visible_films = paginator.page(page)
        except PageNotAnInteger:
            visible_films = paginator.page(1)
        except EmptyPage:
            visible_films = paginator.page(paginator.num_pages)

        context['order_by'] = order_by
        context['direction'] = direction
        context['visible_films'] = visible_films
        context['genre'] = self.kwargs['genre'].capitalize()
        return context


class Top100View(ListView):
    model = Film
    context_object_name = 'top100'

    def get_queryset(self):
        return Film.objects.all().order_by('-score')[:100]

    template_name = 'films/top100.html'


def pages(request):
    order_by = request.GET.get('order_by')
    page = request.GET.get('page')
    direction = request.GET.get('direction')
    ordering = order_by.lower()
    if direction == 'desc':
        ordering = '-{}'.format(ordering)
    films = Film.objects.all().order_by(ordering)
    paginator = Paginator(films, 60)
    try:
        visible_films = paginator.page(page)
    except PageNotAnInteger:
        visible_films = paginator.page(1)
    except EmptyPage:
        visible_films = paginator.page(paginator.num_pages)
    return render(request, 'films/all_films.html',
                  {'visible_films': visible_films,
                   'order_by': order_by, 'direction': direction})


def search_bar(request):
    if request.method == "GET":
        search = request.GET.get("q")
        results = Film.objects.all().filter(Q(title__icontains=search) |
                                  Q(director__icontains=search) |
                                  Q(actors__icontains=search) |
                                  Q(country__icontains=search))
        return render(request, 'films/search_bar.html', {'results': results, 'search': search})

def minigame(request):
    films = list(Film.objects.all())
    rand_film = random.choice(films)
    rand_title = rand_film.title
    rand_film_joined = rand_title.replace(" ", "")
    print(rand_film)
    print(rand_film.title)
    while any(not c.isalnum() for c in rand_film_joined):
        rand_film = random.choice(films)
        rand_title = rand_film.title
        rand_film_joined = rand_title.replace(" ", "")
        print(rand_film)
    return render(request, 'films/minigame.html', {'random_film': rand_film})


@login_required(login_url='login')
def rated(request, film_id):
    if request.method == "POST":
        try:
            reviews = Comment.objects.get(user__id=request.user.id, film__id=film_id)
            rating = reviews.rating
            delete_rating = (reviews.film.score * reviews.film.votes - rating)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            update_rating = (delete_rating + reviews.rating) / reviews.film.votes
            reviews.film.score = update_rating
            reviews.film.save()
            messages.success(request, "Thank you! Your review has been updated!")
            return redirect("films:detail", pk=film_id)
        except Comment.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = Comment()
                data.subject = form.cleaned_data['subject']
                data.comment = form.cleaned_data['comment']
                data.rating = form.cleaned_data['rating']
                data.film_id = film_id
                data.user_id = request.user.id
                data.film.score = (data.film.score * data.film.votes + data.rating) / (data.film.votes + 1)
                data.film.votes += 1
                data.save()
                data.film.save()
                messages.success(request, "Thank you! Your review has been added!")
                return redirect('films:detail', pk=film_id)

films/templates/films/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Filmhub{% endblock %}</title>
    {% load static %}
    <!-- CSS only -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "films/style.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "films/stars.css" %}"/>
    <script src="https://kit.fontawesome.com/613a89ef92.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@700&display=swap" rel="stylesheet">
{#    <script>#}
{#          // Add slideDown animation to Bootstrap dropdown when expanding.#}
{#      $('.dropdown').on('show.bs.dropdown', function() {#}
{#        $(this).find('.dropdown-menu').first().stop(true, true).slideDown(5000);#}
{#      });#}
{##}
{#      // Add slideUp animation to Bootstrap dropdown when collapsing.#}
{#      $('.dropdown').on('hide.bs.dropdown', function() {#}
{#        $(this).find('.dropdown-menu').first().stop(true, true).slideUp(5000);#}
{#      });#}
{#    </script>#}
    {% block include %}
    {% endblock %}

</head>
<body>
    <nav class="navbar sticky-top navbar-expand-md" style="background-color: #1b1b1b;">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'films:index' %}">
                <img src="{% static "films/images/backg_test.png" %}" alt="Filmhub" height="40" width="112">
            </a>
        </div>
        <button type="button" style="border-color: #0091ff; background-color: #1b1b1b;" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navbarNav" aria-expanded="false" aria-controls="navbarNav" aria-label="Toggle navigation">
                <span class="fas fa-bars" style="color: #0091ff;"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'films:pages' %}?page=1&order_by=title&direction=asc" class="nav-link">
                        <span class="fas fa-film" aria-hidden="true"></span>&nbsp;
                        All films
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'films:top_100' %}" class="nav-link">
                        <span class="fas fa-medal" aria-hidden="true"></span>&nbsp;
                        Top 100
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle"
                       id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-expanded="false">
                        <span class="fas fa-sort-alpha-down" aria-hidden="true"></span>&nbsp;
                        Genres
                        <a>
                            <ul class="dropdown-menu" style="max-height: 180px; overflow-y: auto; background-color: #1b1b1b; color: #0091ff; border: 1px solid #0091ff" aria-labelledby="navbarDropdown">
                            {% block genres_loop %}
                                {% for genre in all_genres%}
                                    <li>
                                        <a href="{% url 'films:genre' genre %}?order_by=title&direction=asc" class="dropdown-item">{{ genre }}</a>
                                    </li>
                                {% endfor %}
                            {% endblock %}
                            </ul>
                        </a>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'films:minigame' %}" class="nav-link">
                        <span class="fas fa-gamepad" aria-hidden="true"></span>&nbsp;
                        Minigame
                    </a>
                </li>
            </ul>
            <form class="navbar-form ml-sm-2" autocomplete="off" role="search" method="get" action="{% url 'films:search' %}">
                {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control form-control-sm" style="border-radius: 5px;" id="q" name="q" placeholder="Search" aria-label="Search">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-sm" style="border-color: #0091ff; color: #0091ff; margin-left: 3px; border-radius: 5px;">
                            <span class="fa fa-search" aria-hidden="true"></span>Search</button></span>&nbsp;
                    </div>
            </form>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'profile' %}" class="nav-link">
                        <span class="fas fa-user-circle" aria-hidden="true"></span>&nbsp;
                        My account
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="fas fa-sign-out-alt" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
                {% else %}
                   <li class="nav-item">
                    <a href="{% url 'register' %}" class="nav-link">
                        <span class="fas fa-user-plus" aria-hidden="true"></span>&nbsp;
                        Sign up
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="nav-link">
                        <span class="fas fa-sign-in-alt" aria-hidden="true"></span>&nbsp;
                        Sign in
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% endfor %}
    {% endif %}
{% block body %}
{% endblock %}
{% include "films/scroll_top.html" %}
</body>
</html>

films/templates/films/cards.html
{% load static %}
    {% if films_db %}
    <div class="container">
        <div class="row justify-content-center">
            {% for film in films_db %}
                <div class="col-xs-12 col-sm-6 col-md-4 d-flex justify-content-center">
                    <div class="card border-dark text-white mb-3 p-2" style="max-width: 18rem; background-color: #1b1b1b; width: 280px;">
                        <img class="card-img-top" src="{{ film.poster }}" alt="Poster" onerror="this.onerror=null; this.src='{% static 'films/images/default.gif' %}'" width="240" height="330">
                        <div class="card-body border-primary">
                            <h5>{{ film.title }} {% if film.release_date == 0 %}(Unknown year){% else %}({{ film.release_date }}){% endif %}</h5>
                            <h6>Score: {{ film.score|floatformat:1 }}&nbsp;
                            <span class="fas fa-star" aria-hidden="true"></span>
                            ({{ film.votes }}&nbsp;votes)</h6>
                        </div>
                        <div class="card-footer bg-transparent text-center" style="border-color: #0091ff; border-top: 0px;">
                            <a href="{% url 'films:detail' film.id %}" class="btn btn-outline-primary stretched-link" role="button">
                                    <span class="fas fa-info" aria-hidden="true"></span>&nbsp;Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
    <h1>Ups! There are no films!</h1>
    {% endif %}

films/templates/films/detail.html
{% extends 'films/base.html' %}
{% load static %}
{% block title %}{{ film.title }}{% endblock %}
{% block include %}
<script>
    function bottomFunction() {
            $("html, body").delay(1100).animate({scrollTop:
                document.body.scrollHeight}, 1000);
        }
</script>
{% endblock %}
{% block body %}
    <div class="card mb-3" style="background-color: black;">
    <div class="back-photo" style="position: relative; height: 40%">
      <img class="card-img-top" src="{% static 'films/images/bg_2.jpg' %}" alt="Card image cap" style="">
        <img class="img-fluid" style="position: absolute; width: 20%; height: 85%; left: 40px; bottom: 0; top: 0; margin: auto;" src="{{ film.poster }}" alt="Poster" onerror="this.onerror=null; this.src='{% static 'films/images/default.gif' %}'">
    </div>
        <div class="card-body" style="background-color: #1b1b1b">
            <div class="row">
                <div class="col-md-6 col-sm-12 text-center text-md-left">
                    <h1 class="card-title">{{ film.title }}</h1>
                    <p class="card-text" style="color: white">{% if film.release_date == 0 %}Unknown year{% else %}{{ film.release_date }}{% endif %} &emsp; {{ duration }}</p>
                    <p style="color: white; font-size: 30px;"><span class="fas fa-star" style="color: gold" aria-hidden="true"></span>&nbsp;{{ film.score|floatformat:1 }} ({{ film.votes }}&nbsp;votes)</p>
                </div>
                <div class="col-md-6 col-sm-12 text-center align-self-center">
                    <div id="comment_container" class="dropdown">
                        <button class="btn btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="border: solid 2px #0091ff; color: #0091ff;">
                            Wanna add review?
                        </button>
                    <div class="dropdown-menu dropdown-menu-center" aria-labelledby="dropdownMenuButton" style="margin: 5px; background-color: #1b1b1b; color: white; border: 1px solid black; border-radius: 15px; box-shadow: 3px 3px 30px black;">
                        <div style="margin: 10px;">
                            <h3>Rate this film:</h3>
                        <form action="{% url "films:rated" film.id %}" method="post">
                            {% csrf_token %}
                            <div class="rate">
                                <input  type="radio" name="rating" id="rating10" value="10" required/><label for="rating10" title="10"></label>
                                <input  type="radio" name="rating" id="rating9" value="9" required/><label for="rating9" title="9"></label>
                                <input  type="radio" name="rating" id="rating8" value="8" required/><label for="rating8" title="8"></label>
                                <input  type="radio" name="rating" id="rating7" value="7" required/><label for="rating7" title="7"></label>
                                <input  type="radio" name="rating" id="rating6" value="6" required/><label for="rating6" title="6"></label>
                                <input  type="radio" name="rating" id="rating5" value="5" required/><label for="rating5" title="5"></label>
                                <input  type="radio" name="rating" id="rating4" value="4" required/><label for="rating4" title="4"></label>
                                <input  type="radio" name="rating" id="rating3" value="3" required/><label for="rating3" title="3"></label>
                                <input  type="radio" name="rating" id="rating2" value="2" required/><label for="rating2" title="2"></label>
                                <input  type="radio" name="rating" id="rating1" value="1" required/><label for="rating1" title="1"></label>

                            </div>
                            <div style="display: flex; align-items: center; flex-direction: column;">
                                <label for="subject" hidden="hidden"></label>
                                <input class="form-control" type="text" id="subject" name="subject" placeholder="Title" style="width: 90%;">
                                <label for="comment" hidden="hidden"></label>
                                <textarea rows="5" id=comment name="comment" placeholder="Comment" style="resize: none; width: 90%; margin: 10px 0 10px 0; border-radius: 5px"></textarea>
                            </div>
                            <div style="width: 90%; margin-right: auto; margin-left: auto;">
                                {% if user.is_authenticated %}
                                <input class="btn btn-primary" type="submit" value="Submit" style="border-radius: 10px; float: right;"/>
                                {% else %}
                                    <p>You must be logged in to rate this film. <span><a href="{% url 'login' %}">Login now!</a></span></p>
                                {% endif %}
                            </div>
                        </form>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card text-center" style="background-color: #1b1b1b; margin-left: 25px; margin-right: 25px; margin-top: 35px; margin-bottom: 50px; border-radius: 15px;">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
          <li class="nav-item" style="border-color: #0091ff">
            <a class="nav-link active" data-toggle="tab" href="#details">Details</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#genres">Genres</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#actors" onclick="bottomFunction()">Actors</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#comments">Comments</a>
          </li>
        </ul>
      </div>
      <div class="card-body bg-dark" style="border-bottom-left-radius: 15px; border-bottom-right-radius: 15px;">
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane active fade show text-left" id="details" role="tabpanel" aria-labelledby="details-tab">
                <div class="details_info">
                    <h5 class="disabled" style="color: #0091ff"><span class="fas fa-video" aria-hidden="true"></span>&nbsp;Director:&nbsp;<span style="color: white;">{{ film.director }}</span></h5>
                </div>
                <div class="details_info">
                    <h5 class="disabled" style="color: #0091ff"><span class="fas fa-globe" aria-hidden="true"></span>&nbsp;Country:&nbsp;<span style="color: white">{{ film.country }}</span> </h5>
                </div>
                <div class="details_info">
                    <h5 class="disabled" style="color: #0091ff"><span class="fas fa-calendar-alt" aria-hidden="true"></span>&nbsp;Release year:&nbsp;<span style="color: white">{% if film.release_date == 0 %}Unknown year{% else %}{{ film.release_date }}{% endif %}</span></h5>
                </div>
                <div class="details_info">
                    <h5 class="disabled" style="color: #0091ff"><span class="far fa-clock" aria-hidden="true"></span>&nbsp;Duration:&nbsp;<span style="color: white">{{ duration }}</span></h5>
                </div>
                <div class="details_info">
                    <h5 class="disabled" style="color: #0091ff"><span class="fas fa-star" aria-hidden="true"></span>&nbsp;Score:&nbsp;<span style="color: white">{{ film.score|floatformat:1 }}</span> </h5>
                </div>
                <div class="details-info">
                    <h5 class="disabled" style="color: #0091ff;"><span class="fas fa-plus" aria-hidden="true"></span>&nbsp;Votes:&nbsp;<span style="color: white">{{ film.votes }}</span></h5>
                </div>
            </div>
            <div class="tab-pane fade" id="genres" role="tabpanel" aria-labelledby="genres-tab">
                <ul style="padding: 2px; margin-bottom: 15px; margin-top: 15px">
                    {% for genre in genre_list %}
                            <a role="button" class="btn btn-outline-primary" href="{% url 'films:genre' genre %}?order_by=title&direction=asc"><span class="fas fa-film" aria-hidden="true"></span>&nbsp;{{ genre }}</a>
                    {% empty %}
                        <li>Sorry, no info about genre.</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="tab-pane fade" id="actors" role="tabpanel" aria-labelledby="comment-tab">
                <ul>
                    {% for actor in actors_list %}
                    <li style="list-style-type: none">{{ actor }}</li>
                    {% empty %}
                        <li>Sorry, no info about actors.</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="tab-pane fade" id="comments" role="tabpanel" aria-labelledby="contact-tab" style="overflow-y: scroll; height: 300px;">
                <h4>Reviews</h4><br/>
                {% for comment in comments %}
                    <div class="comment_box">
                        <div style="margin-left: 5px; margin-right: auto; width: 15rem; margin-top: 10px;">
                            <span class="fas fa-star" {% if comment.rating >= 1 %}style="color: gold"{% endif %}></span>
                            <span class="fas fa-star" {% if comment.rating >= 2 %}style="color: gold"{% endif %}></span>
                            <span class="fas fa-star" {% if comment.rating >= 3 %}style="color: gold"{% endif %}></span>
                            <span class="fas fa-star" {% if comment.rating >= 4 %}style="color: gold"{% endif %}></span>
                            <span class="fas fa-star" {% if comment.rating >= 5 %}style="color: gold"{% endif %}></span>
                            <span class="fas fa-star" {% if comment.rating >= 6 %}style="color: gold"{% endif %}></span>
                            <span class="fas fa-star" {% if comment.rating >= 7 %}style="color: gold"{% endif %}></span>
                            <span class="fas fa-star" {% if comment.rating >= 8 %}style="color: gold"{% endif %}></span>
                            <span class="fas fa-star" {% if comment.rating >= 9 %}style="color: gold"{% endif %}></span>
                            <span class="fas fa-star" {% if comment.rating >= 10 %}style="color: gold"{% endif %}></span>
                        </div>
                        <div style="margin-left: 17px; margin-right: auto; text-align: left; margin-top: 5px;">
                            <h5 style="font-weight: 700;">{{ comment.subject }}</h5>
                            <p style="color: lightgray; font-size: x-small; margin-top: 5px;">{{ comment.user }} &emsp; {{ comment.edit_t }}</p>
                            <p style="margin-right: 5px; hyphens: auto;">{{ comment.comment }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
      </div>
    </div>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
{% endblock %}

films/templates/films/form_template.html
{#{% for field in form %}#}
{#    <div class="form-group">#}
{#        <div class="col-sm-offset-2 col-sm-10">#}
{#            <span class="text-danger small">{{ field.errors }}</span>#}
{#        </div>#}
{#        <label class="control-label col-sm-2">{{ field.label_tag }}</label>#}
{#        <div class="col-sm-10">{{ field }}</div>#}
{#    </div>#}
{#{% endfor %}#}

films/templates/films/genres.html
{% extends 'films/base.html' %}
{% block title %}{{ genre }}{% endblock %}
{% block body %}
    <div class="head_box">
        <div class="p-5 text-center bg-black">
            <h1 class="mb-3" style="font-family: Roboto">{{ genre }}</h1>
            <h5 class="mb-3">Page {{ visible_films.number }} of {{ visible_films.paginator.num_pages }}</h5>
        </div>
        {% include 'films/sorting.html' %}
    </div>
    {% include 'films/cards.html' with films_db=visible_films %}
    {% include 'films/paginator.html' with visible_films=visible_films order_by=order_by direction=direction%}
{% endblock %}

films/templates/films/index.html
{% extends 'films/base.html'%}
{% block body %}
    <div class="p-5 text-center bg-black">
        <h1 class="mb-3" style="font-family: Roboto">The latest releases</h1>
    </div>
    {% include 'films/cards.html' with films_db=films_db %}
{% endblock %}

films/templates/films/scroll_top.html
<button onclick="topFunction()"  id="my_btn">
    <span class="fas fa-angle-up"></span>
</button>
<style>
    #my_btn {
  display: none;
  position: fixed;
  z-index: 99;
  border: none;
  outline: none;
  font-size: 18px;
  background-color: #0091ff;
  color: white;
  cursor: pointer;
  border-radius: 5px;
  height: 30px;
  width: 30px;
  left: 1%;
  bottom: 2%;
  padding: 2px;
}
</style>
<script>
    var my_button = document.getElementById("my_btn")

    window.onscroll = function() {scrollFunction()}

    function scrollFunction() {
        if (document.body.scrollTop > 1000 || document.documentElement.scrollTop > 1000) {
            my_button.style.display = "block";
        }
        else {
            my_button.style.display = "none";
        }
    }

    function topFunction() {
        $("html, body").animate({scrollTop: 0}, 500);
    }
</script>